import streamlit as st
import numpy as np
import pandas as pd
import plotly.graph_objects as go
import yfinance as yf
from datetime import datetime, timedelta
from fpdf import FPDF
import requests
import time
import io  # <--- NUEVO IMPORT NECESARIO

# --- CONFIGURACIÓN DE LA APLICACIÓN ---
st.set_page_config(
    page_title="Quantitative Risk Analytics Engine", 
    layout="wide", 
    page_icon="📈"
)

# --- CLASE PDF ---
class PDF(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 15)
        self.cell(0, 10, 'QUANTITATIVE RISK REPORT', 0, 1, 'C')
        self.set_font('Arial', 'I', 10)
        self.cell(0, 10, 'Algorithmic Simulation & Market Analysis Engine', 0, 1, 'C')
        self.line(10, 30, 200, 30)
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()} | Generated by Pro Quant Analytics | {datetime.now().strftime("%Y-%m-%d")}', 0, 0, 'C')

def create_pdf(ticker, current_price, sigma, mu, var_val, cvar_val, conf_level, prob_success, horizon, recommendation):
    pdf = PDF()
    pdf.add_page()
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 10, f'Reporte Ejecutivo para: {ticker}', 0, 1)
    pdf.set_font('Arial', '', 10)
    pdf.cell(0, 10, f'Fecha de Emision: {datetime.now().strftime("%d-%m-%Y %H:%M")}', 0, 1)
    pdf.ln(5)
    pdf.set_fill_color(230, 230, 230)
    pdf.set_font('Arial', 'B', 10)
    pdf.cell(95, 10, "Métrica", 1, 0, 'C', 1)
    pdf.cell(95, 10, "Valor Calculado", 1, 1, 'C', 1)
    pdf.set_font('Arial', '', 10)
    pdf.cell(95, 10, "Precio Actual (Spot)", 1, 0)
    pdf.cell(95, 10, f"{current_price:.2f} USD", 1, 1)
    pdf.cell(95, 10, "Volatilidad Anualizada", 1, 0)
    pdf.cell(95, 10, f"{sigma:.2%}", 1, 1)
    pdf.cell(95, 10, f"Value at Risk (VaR {conf_level:.0%})", 1, 0)
    pdf.cell(95, 10, f"{var_val:.2f} USD", 1, 1)
    pdf.cell(95, 10, f"Conditional VaR (CVaR)", 1, 0)
    pdf.cell(95, 10, f"{cvar_val:.2f} USD", 1, 1)
    pdf.cell(95, 10, "Horizonte de Proyeccion", 1, 0)
    pdf.cell(95, 10, f"{horizon} Dias Operativos", 1, 1)
    pdf.ln(10)
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 10, 'Diagnostico Algoritmico', 0, 1)
    pdf.set_font('Arial', '', 11)
    pdf.multi_cell(0, 7, f"Basado en {recommendation['n_sims']} simulaciones de Montecarlo, el modelo presenta una probabilidad de retorno positivo del {prob_success:.1%}.\n\n")
    pdf.set_font('Arial', 'B', 11)
    pdf.cell(0, 10, f"Recomendacion Tecnica: {recommendation['signal']}", 0, 1)
    pdf.set_font('Arial', '', 11)
    pdf.multi_cell(0, 7, f"Analisis: {recommendation['advice']}\n")
    pdf.ln(5)
    pdf.multi_cell(0, 7, f"Perfil de Riesgo: Se ha detectado una volatilidad del {sigma:.1%}. Se sugiere establecer un Stop Loss tecnico en {var_val:.2f} USD para limitar la exposicion a perdidas mas alla del nivel de confianza del {conf_level:.0%}.")
    pdf.ln(20)
    pdf.set_font('Arial', 'I', 8)
    pdf.multi_cell(0, 5, "DISCLAIMER: Este reporte es generado automaticamente por un modelo estocastico. Los resultados son probabilisticos y no garantizan rendimientos futuros. No constituye asesoramiento financiero certificado.")
    return pdf.output(dest='S').encode('latin-1')

# --- ACTIVOS ---
ASSET_UNIVERSE = {
    "🔍 Entrada Manual (Ticker)": "MANUAL",
    "🇺🇸 Tesla Inc. (TSLA)": "TSLA",
    "🇺🇸 Apple Inc. (AAPL)": "AAPL",
    "🇺🇸 NVIDIA Corp. (NVDA)": "NVDA",
    "🇺🇸 Microsoft Corp. (MSFT)": "MSFT",
    "🇺🇸 Amazon.com Inc. (AMZN)": "AMZN",
    "🇺🇸 S&P 500 ETF (SPY)": "SPY",
    "🥇 Gold Futures (GC=F)": "GC=F",
    "₿ Bitcoin USD (BTC-USD)": "BTC-USD"
}

# --- INGESTA HÍBRIDA (YAHOO + STOOQ DIRECTO) ---
@st.cache_data(ttl=3600, show_spinner=False)
def fetch_market_data(symbol):
    """
    Sistema de Ingesta Híbrido:
    1. Yahoo Finance (Metadata rica).
    2. Stooq Direct CSV (Sin librería rota pandas_datareader).
    """
    
    data_source = "None"
    df = pd.DataFrame()
    asset_info = {}
    
    # Configurar sesión global
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/120.0.0.0 Safari/537.36'}
    session = requests.Session()
    session.headers.update(headers)
    
    # ---------------------------------------------------------
    # INTENTO 1: YAHOO FINANCE (PRIMARIO)
    # ---------------------------------------------------------
    try:
        print(f"[INFO] Intentando conectar con Yahoo Finance para {symbol}...")
        stock = yf.Ticker(symbol, session=session)
        df = stock.history(period="2y")
        
        if not df.empty:
            data_source = "Yahoo Finance"
            try:
                info_curr = stock.info.get('currency', 'USD')
                info_name = stock.info.get('longName', symbol)
            except:
                info_curr = 'USD'
                info_name = symbol
            
            asset_info = {"currency": info_curr, "name": info_name}

    except Exception as e:
        print(f"[WARN] Yahoo Finance falló: {e}")

    # ---------------------------------------------------------
    # INTENTO 2: STOOQ DIRECTO (SECUNDARIO)
    # ---------------------------------------------------------
    if df.empty:
        print(f"[INFO] Activando Protocolo Failover: STOOQ DIRECTO para {symbol}...")
        try:
            # Stooq usa tickers como 'AAPL.US' o 'BTC-USD'. Intentamos sufijo si falla el base.
            tickers_to_try = [symbol, f"{symbol}.US"]
            
            for t_try in tickers_to_try:
                # Descarga directa del CSV de Stooq (sin pandas_datareader)
                url = f"https://stooq.com/q/d/l/?s={t_try}&i=d"
                response = session.get(url)
                
                if response.status_code == 200 and "No data" not in response.text:
                    df_stooq = pd.read_csv(io.StringIO(response.text), index_col="Date", parse_dates=True)
                    
                    if not df_stooq.empty:
                        df = df_stooq
                        # Filtrar últimos 2 años
                        start_date = datetime.now() - timedelta(days=730)
                        df = df[df.index >= start_date]
                        
                        data_source = "Stooq (Backup)"
                        df = df.sort_index()
                        asset_info = {"currency": "USD", "name": f"{symbol} (Data from Stooq)"}
                        break 
                        
        except Exception as e:
            print(f"[ERROR] Stooq también falló: {e}")

    # ---------------------------------------------------------
    # PROCESAMIENTO FINAL
    # ---------------------------------------------------------
    if df.empty:
        return None, None, None 

    try:
        # Normalización de columnas (Stooq usa mayúsculas, Yahoo Title Case)
        df.columns = [c.capitalize() for c in df.columns]
        
        if 'Close' not in df.columns:
            return None, None, None

        # Cálculos matemáticos
        df['Log_Ret'] = np.log(df['Close'] / df['Close'].shift(1))
        df.dropna(inplace=True)
        
        last_price = df['Close'].iloc[-1]
        volatility = df['Log_Ret'].std() * np.sqrt(252)
        historical_drift = df['Log_Ret'].mean() * 252
        
        asset_info["price"] = float(last_price)
        if "currency" not in asset_info: asset_info["currency"] = "USD"
        if "name" not in asset_info: asset_info["name"] = symbol

        return df, (volatility, historical_drift, asset_info), data_source

    except Exception as e:
        print(f"[ERROR] Error matemático: {e}")
        return None, None, None

# --- MOTOR DE SIMULACIÓN ---
def run_simulation(S0, mu, sigma, T, N, dt, jumps, lambda_j, mu_j, sigma_j):
    prices = np.zeros((T + 1, N))
    prices[0] = S0
    for t in range(1, T + 1):
        z = np.random.normal(0, 1, N)
        diffusion = (mu - 0.5 * sigma**2) * dt + sigma * np.sqrt(dt) * z
        jump_term = 0
        if jumps:
            n_jumps = np.random.poisson(lambda_j * dt, N)
            if np.any(n_jumps > 0):
                jump_term = np.random.normal(mu_j, sigma_j, N) * n_jumps
        prices[t] = prices[t-1] * np.exp(diffusion + jump_term)
    return prices

# --- INTERFAZ ---
st.title("📈 Quantitative Risk Analytics Engine")
st.markdown("Sistema de Simulación Estocástica y Valoración de Riesgo de Mercado. Arquitectura redundante (Yahoo/Stooq).")

# Sidebar
st.sidebar.header("1. Configuración")
sel = st.sidebar.selectbox("Activo:", list(ASSET_UNIVERSE.keys()), index=1)
ticker = st.sidebar.text_input("Ticker:", value="GOOGL").upper() if ASSET_UNIVERSE[sel] == "MANUAL" else ASSET_UNIVERSE[sel]

st.sidebar.divider()
st.sidebar.header("2. Simulación")
T_days = st.sidebar.slider("Días", 5, 365, 30)
N_sims = st.sidebar.selectbox("Escenarios", [1000, 5000, 10000], index=1)

st.sidebar.divider()
st.sidebar.header("3. Modelo (Quant)")
with st.sidebar.expander("⚙️ Calibración", expanded=False):
    ov_drift = st.checkbox("Sobrescribir Drift")
    m_drift = st.slider("Drift %", -50.0, 100.0, 10.0) / 100
    jumps = st.checkbox("Saltos (Merton)", True)
    j_prob = st.slider("Probabilidad", 0.0, 50.0, 5.0) / 100
    j_mean = st.slider("Magnitud %", -30.0, 30.0, -5.0) / 100
    j_std = st.slider("Volatilidad Salto %", 0.0, 50.0, 10.0) / 100
    conf = st.selectbox("VaR Confianza", [0.90, 0.95, 0.99], index=1)

# Main Execution
if st.button(f"⚡ EJECUTAR ANÁLISIS PARA {ticker}", type="primary"):
    with st.spinner("Estableciendo conexión con proveedores de datos..."):
        hist, metrics, source = fetch_market_data(ticker)
    
    if hist is None:
        st.error(f"❌ Error Crítico: No se pudo obtener datos de {ticker} en ninguno de los proveedores (Yahoo/Stooq). Verifica el Ticker.")
    else:
        sigma, mu_h, info = metrics
        S0 = info['price']
        mu_f = m_drift if ov_drift else mu_h
        
        if source == "Yahoo Finance":
            st.success(f"✅ Datos obtenidos vía Yahoo Finance API (Principal).")
        else:
            st.warning(f"⚠️ Yahoo Finance no responde. Datos obtenidos vía Stooq (Respaldo).")

        sims = run_simulation(S0, mu_f, sigma, T_days, N_sims, 1/252, jumps, j_prob, j_mean, j_std)
        final_P = sims[-1]
        
        # Riesgo
        alpha = 1 - conf
        VaR = np.percentile(final_P, alpha * 100)
        CVaR = final_P[final_P <= VaR].mean()
        P_succ = np.sum(final_P > S0) / N_sims
        
        if P_succ > 0.65: sig, adv = "BULLISH", "Tendencia alcista fuerte detectada."
        elif P_succ < 0.35: sig, adv = "BEARISH", "Tendencia bajista. Precaución."
        else: sig, adv = "NEUTRAL", "Mercado lateral sin tendencia clara."

        # Dashboard
        c1, c2, c3 = st.columns(3)
        c1.metric("Precio Spot", f"{S0:.2f} {info['currency']}")
        c2.metric("VaR Estimado", f"{VaR:.2f}")
        c3.metric("Prob. Éxito", f"{P_succ:.1%}")
        
        t1, t2 = st.tabs(["Trayectorias", "Reporte PDF"])
        with t1:
            st.line_chart(sims[:, :100])
        with t2:
            pdf_data = create_pdf(ticker, S0, sigma, mu_f, VaR, CVaR, conf, P_succ, T_days, {'signal':sig, 'advice':adv, 'n_sims':N_sims})
            st.download_button("📄 DESCARGAR PDF OFICIAL", pdf_data, file_name=f"Reporte_{ticker}.pdf", mime="application/pdf")