import streamlit as st
import numpy as np
import pandas as pd
import plotly.graph_objects as go
import yfinance as yf
from datetime import datetime, timedelta
from fpdf import FPDF
import base64

# --- CONFIGURACIÓN DE LA APLICACIÓN ---
st.set_page_config(
    page_title="Quantitative Risk Analytics Engine", 
    layout="wide", 
    page_icon="📈"
)

# --- CLASE PARA GENERAR PDF PROFESIONAL ---
class PDF(FPDF):
    def header(self):
        # Logo o Título Corporativo
        self.set_font('Arial', 'B', 15)
        self.cell(0, 10, 'QUANTITATIVE RISK REPORT', 0, 1, 'C')
        self.set_font('Arial', 'I', 10)
        self.cell(0, 10, 'Algorithmic Simulation & Market Analysis Engine', 0, 1, 'C')
        self.line(10, 30, 200, 30)
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()} | Generated by Pro Quant Analytics | {datetime.now().strftime("%Y-%m-%d")}', 0, 0, 'C')

def create_pdf(ticker, current_price, sigma, mu, var_val, cvar_val, conf_level, prob_success, horizon, recommendation):
    pdf = PDF()
    pdf.add_page()
    
    # 1. ENCABEZADO DEL REPORTE
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 10, f'Reporte Ejecutivo para: {ticker}', 0, 1)
    pdf.set_font('Arial', '', 10)
    pdf.cell(0, 10, f'Fecha de Emision: {datetime.now().strftime("%d-%m-%Y %H:%M")}', 0, 1)
    pdf.ln(5)

    # 2. TABLA DE MÉTRICAS CLAVE
    pdf.set_fill_color(230, 230, 230)
    pdf.set_font('Arial', 'B', 10)
    pdf.cell(95, 10, "Métrica", 1, 0, 'C', 1)
    pdf.cell(95, 10, "Valor Calculado", 1, 1, 'C', 1)

    pdf.set_font('Arial', '', 10)
    pdf.cell(95, 10, "Precio Actual (Spot)", 1, 0)
    pdf.cell(95, 10, f"{current_price:.2f} USD", 1, 1)
    
    pdf.cell(95, 10, "Volatilidad Anualizada", 1, 0)
    pdf.cell(95, 10, f"{sigma:.2%}", 1, 1)
    
    pdf.cell(95, 10, f"Value at Risk (VaR {conf_level:.0%})", 1, 0)
    pdf.cell(95, 10, f"{var_val:.2f} USD", 1, 1)
    
    pdf.cell(95, 10, f"Conditional VaR (CVaR)", 1, 0)
    pdf.cell(95, 10, f"{cvar_val:.2f} USD", 1, 1)

    pdf.cell(95, 10, "Horizonte de Proyeccion", 1, 0)
    pdf.cell(95, 10, f"{horizon} Dias Operativos", 1, 1)
    pdf.ln(10)

    # 3. INTERPRETACIÓN Y DIAGNÓSTICO
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 10, 'Diagnostico Algoritmico', 0, 1)
    
    pdf.set_font('Arial', '', 11)
    pdf.multi_cell(0, 7, f"Basado en {recommendation['n_sims']} simulaciones de Montecarlo, el modelo presenta una probabilidad de retorno positivo del {prob_success:.1%}.\n\n")
    
    pdf.set_font('Arial', 'B', 11)
    pdf.cell(0, 10, f"Recomendacion Tecnica: {recommendation['signal']}", 0, 1)
    
    pdf.set_font('Arial', '', 11)
    pdf.multi_cell(0, 7, f"Analisis: {recommendation['advice']}\n")
    
    pdf.ln(5)
    pdf.multi_cell(0, 7, f"Perfil de Riesgo: Se ha detectado una volatilidad del {sigma:.1%}. Se sugiere establecer un Stop Loss tecnico en {var_val:.2f} USD para limitar la exposicion a perdidas mas alla del nivel de confianza del {conf_level:.0%}.")

    # 4. DISCLAIMER
    pdf.ln(20)
    pdf.set_font('Arial', 'I', 8)
    pdf.multi_cell(0, 5, "DISCLAIMER: Este reporte es generado automaticamente por un modelo estocastico. Los resultados son probabilisticos y no garantizan rendimientos futuros. No constituye asesoramiento financiero certificado.")
    
    return pdf.output(dest='S').encode('latin-1')

# --- CATÁLOGO DE ACTIVOS FINANCIEROS ---
ASSET_UNIVERSE = {
    "🔍 Entrada Manual (Ticker)": "MANUAL",
    "🇺🇸 Tesla Inc. (TSLA)": "TSLA",
    "🇺🇸 Apple Inc. (AAPL)": "AAPL",
    "🇺🇸 NVIDIA Corp. (NVDA)": "NVDA",
    "🇺🇸 Microsoft Corp. (MSFT)": "MSFT",
    "🇺🇸 Amazon.com Inc. (AMZN)": "AMZN",
    "🇺🇸 S&P 500 ETF (SPY)": "SPY",
    "🥇 Gold Futures (GC=F)": "GC=F",
    "₿ Bitcoin USD (BTC-USD)": "BTC-USD"
}

# --- SISTEMA DE LOGS ---
def sys_log(message, level="INFO"):
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S.%f")[:-3]
    print(f"[{timestamp}] [{level}] {message}")

# --- TÍTULO ---
st.title("📈 Quantitative Risk Analytics Engine")
st.markdown("""
**Sistema de Simulación Estocástica y Valoración de Riesgo de Mercado.**
Generación de reportes PDF profesionales basados en modelos de *Merton Jump Diffusion*.
""")

# --- BARRA LATERAL ---
st.sidebar.header("1. Configuración del Activo")
selected_option = st.sidebar.selectbox("Instrumento Financiero:", list(ASSET_UNIVERSE.keys()), index=1)
if ASSET_UNIVERSE[selected_option] == "MANUAL":
    ticker = st.sidebar.text_input("Ingresar Ticker:", value="GOOGL").upper()
else:
    ticker = ASSET_UNIVERSE[selected_option]

st.sidebar.divider()
st.sidebar.header("2. Parámetros de Simulación")
time_horizon = st.sidebar.slider("Horizonte (Días)", 5, 365, 30)
n_simulations = st.sidebar.selectbox("Iteraciones Montecarlo", [1000, 5000, 10000], index=1)

st.sidebar.divider()
st.sidebar.header("3. Ajuste de Modelo (Quant)")
with st.sidebar.expander("⚙️ Calibración Avanzada", expanded=False):
    override_drift = st.checkbox("Sobrescribir Drift (View)")
    manual_drift = st.slider("Drift Anual (%)", -50.0, 100.0, 10.0, step=0.5) / 100
    enable_jumps = st.checkbox("Habilitar Saltos (Merton)", value=True)
    jump_prob = st.slider("Probabilidad Salto", 0.0, 50.0, 5.0) / 100
    jump_mean = st.slider("Magnitud Salto (%)", -30.0, 30.0, -5.0) / 100
    jump_std = st.slider("Volatilidad Salto (%)", 0.0, 50.0, 10.0) / 100
    confidence_level = st.selectbox("Nivel Confianza (VaR)", [0.90, 0.95, 0.99], index=1)

# --- INGESTA DE DATOS ---
@st.cache_data(ttl=3600, show_spinner=False)
def fetch_market_data(symbol):
    sys_log(f"Fetching data for: {symbol}")
    try:
        stock = yf.Ticker(symbol)
        df = stock.history(period="2y")
        if df.empty: return None, None
        
        df['Log_Ret'] = np.log(df['Close'] / df['Close'].shift(1))
        df.dropna(inplace=True)
        
        last_price = df['Close'].iloc[-1]
        volatility = df['Log_Ret'].std() * np.sqrt(252)
        historical_drift = df['Log_Ret'].mean() * 252
        
        asset_info = {"price": last_price, "currency": stock.info.get('currency', 'USD'), "name": stock.info.get('longName', symbol)}
        return df, (volatility, historical_drift, asset_info)
    except Exception: return None, None

# --- SIMULACIÓN ---
def run_simulation(S0, mu, sigma, T, N, dt, jumps, lambda_j, mu_j, sigma_j):
    prices = np.zeros((T + 1, N))
    prices[0] = S0
    for t in range(1, T + 1):
        z = np.random.normal(0, 1, N)
        diffusion = (mu - 0.5 * sigma**2) * dt + sigma * np.sqrt(dt) * z
        jump_term = 0
        if jumps:
            n_jumps = np.random.poisson(lambda_j * dt, N)
            if np.any(n_jumps > 0):
                jump_term = np.random.normal(mu_j, sigma_j, N) * n_jumps
        prices[t] = prices[t-1] * np.exp(diffusion + jump_term)
    return prices

# --- MAIN ---
if st.button(f"⚡ EJECUTAR ANÁLISIS PARA {ticker}", type="primary"):
    with st.spinner("Procesando Simulación y Generando Informe..."):
        hist_data, metrics = fetch_market_data(ticker)
        
    if hist_data is None:
        st.error("Error de datos.")
    else:
        sigma_base, mu_hist, info = metrics
        S0 = info['price']
        mu_final = manual_drift if override_drift else mu_hist
        
        sim_results = run_simulation(S0, mu_final, sigma_base, time_horizon, n_simulations, 1/252, enable_jumps, jump_prob, jump_mean, jump_std)
        final_prices = sim_results[-1]
        
        # Cálculos de Riesgo
        alpha = 1 - confidence_level
        var_val = np.percentile(final_prices, alpha * 100)
        cvar_val = final_prices[final_prices <= var_val].mean()
        prob_success = np.sum(final_prices > S0) / n_simulations

        # Lógica de Recomendación (Texto)
        if prob_success > 0.65:
            signal = "BULLISH (ALCISTA)"
            advice = "El modelo sugiere acumulacion. Probabilidad de exito estadisticamente alta."
        elif prob_success < 0.35:
            signal = "BEARISH (BAJISTA)"
            advice = "Se sugiere cobertura o salida. Tendencia negativa predominante."
        else:
            signal = "NEUTRAL (RANGO)"
            advice = "Incertidumbre elevada. No hay ventaja estadistica clara."

        # VISUALIZACIÓN
        kpi1, kpi2, kpi3 = st.columns(3)
        kpi1.metric("Precio Spot", f"{S0:.2f}")
        kpi2.metric("VaR Estimado", f"{var_val:.2f}")
        kpi3.metric("Prob. Éxito", f"{prob_success:.1%}")
        
        tab1, tab2 = st.tabs(["📈 Gráficos", "📄 Reporte PDF"])
        
        with tab1:
            st.subheader("Trayectorias Montecarlo")
            st.line_chart(sim_results[:, :100]) # Muestra rápida simple
        
        with tab2:
            st.subheader("Generación de Documentos")
            st.write("El informe ejecutivo en PDF incluye el análisis de riesgo, diagnóstico algorítmico y parámetros técnicos.")
            
            # Generar PDF
            rec_data = {'signal': signal, 'advice': advice, 'n_sims': n_simulations}
            pdf_bytes = create_pdf(ticker, S0, sigma_base, mu_final, var_val, cvar_val, confidence_level, prob_success, time_horizon, rec_data)
            
            st.download_button(
                label="📄 DESCARGAR INFORME PROFESIONAL (PDF)",
                data=pdf_bytes,
                file_name=f"Reporte_Riesgo_{ticker}.pdf",
                mime="application/pdf"
            )